### ISSUE TITLE
Add support for managing data redaction

### ISSUE THREAD

**Issue by jaywryan** [RedHatInsights/ansible-collections-insights#21]
as part of the management of the client configuration with the insights role.  I would to have the ability to manage the different ways to obfuscate the insights data.  Specifically:

- manage IP and hostname obfuscation in insights-client.conf
- manage the file-redaction.yaml & file-content-redaction.yaml files

**Comment by ptoscano** [comment]
The preferred Ansible way to connect Red Hat system to RHSM and Insights is the "rhc" system role [1]. New use cases & features related to the connection of a system to Insights should be implemented there. As of the release of version 1.3.0, the bits related to insights-client are officially deprecated. 

Hence, I'm closing this request as "wontfix". Thanks anyway for the report.

[1] https://github.com/linux-system-roles/rhc/
