### ISSUE TITLE
Unable to get system tags using get_tags

### ISSUE THREAD

**Issue by jangel97** [RedHatInsights/ansible-collections-insights#28]
Hi,

I am trying to get tags information in Insights but it seems `get_tags` option is not working.

The error I am getting is the following:
```
[WARNING]:  * Failed to parse /Users/jmorenas/Desktop/my_stuff/insights-inventory/insights.yml with insights plugin: ('Connection
aborted.', RemoteDisconnected('Remote end closed connection without response'))
  File "/usr/local/lib/python3.9/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/Users/jmorenas/Desktop/my_stuff/insights-inventory/inventory_plugins/insights.py", line 253, in parse
    system_tags = self.get_tags(systems_by_id.keys())
  File "/Users/jmorenas/Desktop/my_stuff/insights-inventory/inventory_plugins/insights.py", line 135, in get_tags
    response = self.session.get(url, auth=self.auth, headers=self.headers)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
```

My environment is the following:
```
jmorenas-mac:insights-inventory jmorenas$ ansible --version
ansible 2.9.7
  config file = /Users/jmorenas/Desktop/my_stuff/insights-inventory/ansible.cfg
  configured module search path = ['/Users/jmorenas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 06:20:32) [Clang 12.0.0 (clang-1200.0.32.29)]
```

Some considerations:
- I suspect the issue is going on when attempting connection here: https://github.com/RedHatInsights/ansible-collections-insights/blob/master/plugins/inventory/insights.py#L135
- This issue only happens when there is a large number of ansible managed hosts (in my case approximately 1700). When running code with fewer hosts it will work. This makes me think that tuning API on server side could help.
- Adding high timeout to connection in source code does not help either.

Jus wanted to bring this up to you guys, so you can be aware of this issue.

Thanks in advance,

**Comment by AlanCoding** [comment]
What version of the collection are you using and how did you install it? The line numbers don't match current master branch.

**Comment by jangel97** [comment]
Hi, 

I have tested https://github.com/RedHatInsights/ansible-collections-insights/pull/34 in my environment (ansible 2.9 and python 3.9), and it works. As I see it this is an issue on the API side, let me explain why.

Basically, the plugin inventory is sending all of the systems to the tags endpoint, comma separated, in the following way: 
```
api/inventory/v1/hosts/system_id_1,system_id_2,system_id_3,..,system_id_4/tags?per_page=50
```
https://github.com/RedHatInsights/ansible-collections-insights/blob/master/plugins/inventory/insights.py#L160

The comma separated list of IDs is concatenated via `.join(ids)`

When you pass more than 50 hosts to the `tags` API endpoint, it returns "Connection aborted". That is why the PR fixes the issue, because then the tags API endpoint processes smaller chunks.

I guess this behaviour should be documented in Insights API docs?

**Comment by kruai** [comment]
> 

@jangel97 In my experience, "Connection aborted" generally points to a URL issue. In this case, since you're making an API call with > 50 hosts in the path, I would assume that you're hitting the upper limit of what's allowed for a URL. The maximum length is generally ~2,000 characters, which you'd hit at 52-53 hosts, assuming `?per_page=50` is the only request param being added.
