### ISSUE TITLE
Failed (/etc/insights-client/machine-id) is absent, cannot continue

### ISSUE THREAD

**Issue by jangel97** [RedHatInsights/ansible-collections-insights#45]
Hello there,

I noticed an issue which is breaking the configuration on our systems.

Apparently the role RedHatInsights.insights-client is failing for my rhel8 host with following message `file (/etc/insights-client/machine-id) is absent, cannot continue`. The name of the failing task is `RedHatInsights.insights-client : Change permissions of machine_id file so that Insights System ID can be read`.

The fact that machine-id does not exist, implies that the host is not registered to Insights, and actually if I run following command: 
```
[root@tower-isolated1 plays]# insights-client --status
This host is unregistered.
```
It indeed replies that the system is not registered. And if I check the return code of the command it's 0.
```
[root@tower-isolated1 plays]# echo $?
0
```

It looks to me that the task `RedHatInsights.insights-client : Register Insights Client` is not properly working, since this is what it is returning:
```
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "display_name": "",
            "force_reregister": false,
            "insights_name": "insights-client",
            "state": "present"
        }
    },
    "message": "The Insights API has determined that this machine is already registered",
    "original_message": "Attempting to register insights-client"
}
```

My assumption is that this https://github.com/RedHatInsights/ansible-collections-insights/blob/master/plugins/modules/insights_register.py#L131 conditional is missing some logic.

Let me know your thoughts. 

Thanks,

**Comment by ptoscano** [comment]
It looks like #46 fixed the issue, so closing.

Thanks!
