### ISSUE TITLE
Insights ansible inventory plugin (insights.py) fails to retrieve large inventory

### ISSUE THREAD

**Issue by mjpalacios** [RedHatInsights/ansible-collections-insights#48]
In method InventoryModule.parse, lines 233 through 250, a URL is constructed from page numbers and filtering tags. If the underlying collection is large enough the URL gets bigger that 4096 characters and that hits an underlying limit in the backend (cloud.redhat.com) which results in the plugin erroring with the following message:

redhat_insights.yml with
auto plugin: http error (400): <html>   <head>     <title>Bad Request</title>
</head>   <body>     <h1><p>Bad Request</p></h1>     Request Line is too large
(4098 &gt; 4094)   </body> </html>

**Comment by ptoscano** [comment]
This was fixed by #49, thus closing.
