### ISSUE TITLE
SSO credential-based authentication (basic authentication) has been deprecated for security reasons.

### ISSUE THREAD

**Issue by m8ram** [RedHatInsights/ansible-collections-insights#87]
As documented in [Appendix E of the Red Hat Insights documentation](https://access.redhat.com/documentation/en-us/red_hat_insights/2023/html/client_configuration_guide_for_red_hat_insights/assembly-client-data-cg-basic-authentication):

> SSO credential-based authentication (basic authentication) has been deprecated for security reasons. Consider using a more secure authentication method, such as certificate-based authentication.

https://github.com/RedHatInsights/ansible-collections-insights/blob/22dfe8e8cd69f0ab6378732678a3e9b1db6f8866/plugins/inventory/insights.py#L237 uses HTTPBasicAuth

**Comment by ptoscano** [comment]
It looks like that appendix was removed from the documentation.

For the actual ticket: #98 implements authentication using service accounts.
