### ISSUE TITLE
Feature request: assign host to Inventory group

### ISSUE THREAD

**Issue by m8ram** [RedHatInsights/ansible-collections-insights#88]
Now that [Inventory Groups](https://access.redhat.com/documentation/en-us/red_hat_insights/2023/html/viewing_and_managing_system_inventory/deploying-insights-with-rhca) are live the ansible role should allow the user to set the Inventory group.

To be clear the goal is not to use the current `--group=GROUP` option of insights client which adds a tag but does not add the system to an Inventory Group.

**Comment by m8ram** [comment]
Thanks @ptoscano , I'm discussing exactly that internally with the product managers in parallel.

**Comment by ptoscano** [comment]
As reference: the request to change the `--groups` option of `insights-client` is https://github.com/RedHatInsights/insights-client/issues/156.

**Comment by ptoscano** [comment]
The preferred Ansible way to connect Red Hat system to RHSM and Insights is the "rhc" system role [1]. New use cases & features related to the connection of a system to Insights should be implemented there. As of the release of version 1.3.0, the bits related to insights-client are officially deprecated. 

As mentioned already, this needs work first in insights-client, so it can be implemented later on. Regarding the Ansible implementation, the "rhc" role is the place where to implement it, so please open a request about it for the role.

As for this PR: I'm closing this, as no new features will be implemented in the insights-client bits.

[1] https://github.com/linux-system-roles/rhc/
